/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as ProfissionaisIdRouteImport } from './routes/profissionais.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisIdRoute = ProfissionaisIdRouteImport.update({
  id: '/profissionais/$id',
  path: '/profissionais/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pagamentos': typeof PagamentosRoute
  '/profissionais/$id': typeof ProfissionaisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pagamentos': typeof PagamentosRoute
  '/profissionais/$id': typeof ProfissionaisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pagamentos': typeof PagamentosRoute
  '/profissionais/$id': typeof ProfissionaisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pagamentos' | '/profissionais/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pagamentos' | '/profissionais/$id'
  id: '__root__' | '/' | '/pagamentos' | '/profissionais/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagamentosRoute: typeof PagamentosRoute
  ProfissionaisIdRoute: typeof ProfissionaisIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais/$id': {
      id: '/profissionais/$id'
      path: '/profissionais/$id'
      fullPath: '/profissionais/$id'
      preLoaderRoute: typeof ProfissionaisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagamentosRoute: PagamentosRoute,
  ProfissionaisIdRoute: ProfissionaisIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
